### ISSUE TITLE
Rename the project

### ISSUE THREAD

**Issue by piotrd** [2fdevs/bower-videogular#10]
Hi,

Have you thought about renaming the project, as it is not only used for publishing to bower registry, but also to npm?

**Comment by 2fdevs** [comment]
It is published on NPM:

videogula-angulartics - v1.3.1 - bower-videogular-analytics
videogular - v1.3.2 - bower-videogular
videogular-angulartics - v1.3.2 - bower-videogular-analytics
videogular-buffering - v1.3.2 - bower-videogular-buffering
videogular-controls - v1.3.2 - bower-videogular-controls
videogular-dash - v1.3.2 - bower-videogular-dash
videogular-ima-ads - v1.3.2 - bower-videogular-ima-ads
videogular-overlay-play - v1.3.2 - bower-videogular-overlay-play
videogular-poster - v1.3.2 - bower-videogular-poster
videogular-themes-default - v1.3.2 - bower-videogular-themes-default
