### ISSUE TITLE
add tag for bumped angular js version

### ISSUE THREAD

**Issue by leipert** [2fdevs/bower-videogular#2]
Could you add a tag like `0.8.0` for the bumped angularjs version?

**Comment by 2fdevs** [comment]
We're busy right now with the next release 1.0.0. Can you just delete and download again the repo? It should work.

**Comment by Frank3K** [comment]
+1

I have installed videoangular with `bower install videogular#master`, which gives the correct version of AngularJS. Unfortunately the plugins (e.g. videogular-controls) reference the `latest` version of videogular, which is 0.7.2.

---

For anyone wanting to use the plugins:
- controls: `bower install --save Frank3K/bower-videogular-controls#master`
- default theme: `bower install --save Frank3K/bower-videogular-themes-default#master`

**Comment by 2fdevs** [comment]
I've been updated all repos and bower configs.

It should work now.
