### ISSUE TITLE
Maybe: Wrong dependency versions in Master / v0.7.2 ?

### ISSUE THREAD

**Issue by linslin** [2fdevs/bower-videogular#3]
Hi,

currently I cant install videogular via bower using angular 1.3.7 because dependencies in 
https://github.com/2fdevs/bower-videogular/blob/master/bower.json aiming on angular 1.2.x

Current master's dependencies are focusing 1.3.x
https://github.com/2fdevs/bower-videogular/blob/v0.7.2/bower.json

Is this a mistake?

**Comment by 2fdevs** [comment]
Yes, this is related with #2 and we're working on v1.0.0 that will solve this problems very soon.

**Comment by linslin** [comment]
https://github.com/2fdevs/bower-videogular/issues/2 is still open. Soon? =)

**Comment by 2fdevs** [comment]
Yes, I will try to fix this issue and #4 this week.

**Comment by 2fdevs** [comment]
As I said in #4 I will fix this for v1.0.0 but not previous releases in order to maintain what people could expect.
