### ISSUE TITLE
Bower still pulling 1.0.0

### ISSUE THREAD

**Issue by ndcollins** [2fdevs/bower-videogular#6]
Even if I explicitly set bower to pull 1.0.1, it is still pulling 1.0.0 which for me is missing the vgMedia directive.

**Comment by 2fdevs** [comment]
I've tried and it worked for me with just `bower install videogular`.

Maybe you have a cache problem.

**Comment by ndcollins** [comment]
That's what I thought, but I ran `bower cache clean` and I'm still just getting 1.0.0

**Comment by 2fdevs** [comment]
Can you try in other pc? I've just tried and it works here.

**Comment by 2fdevs** [comment]
Can you try now? Actually we solved some problems in bower.

Thanks for the warning.
