### ISSUE TITLE
Stable branch

### ISSUE THREAD

**Issue by AprilArcus** [2fdevs/bower-videogular#7]
Since videogular is still not on npm (c.f. https://github.com/2fdevs/videogular/issues/176), would you mind creating a branch of the bower repo and locking it at the most recent stable version so that we can reference it from our project's package.json?

**Comment by 2fdevs** [comment]
Maybe you can try by targeting the tag as proposed here:

http://stackoverflow.com/questions/14187956/npm-install-from-git-in-a-specific-version

Is this a valid solution for you?

**Comment by AprilArcus** [comment]
Thank you, this works great for now.

**Comment by 2fdevs** [comment]
Great, closing.

BTW, we will change to NPM with Videogular 2.0.

**Comment by mchambaud** [comment]
@2fdevs can we expect Videogular anytime soon?

**Comment by 2fdevs** [comment]
Nope, it's under development and it will be released for Angular 2.0.

So until Angular 2.0 is not released we're not going to make any stable release. However, if you're curious and want to contribute you can take a look to it in this branch:

https://github.com/2fdevs/videogular/tree/RC-2.0.0-alpha
